title : Personal

safe: true
lsi: false
pygments: true
auto: true

source: personal
destination: personal

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 10
paginate_path: "/blog/page:num"

production_url : http://personal.kinlane.com

BASE_PATH : http://personal.kinlane.com

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
